config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  resources :users
  
  resources :comments do
    member do
      post :like
      post :dislike
    end
  end
    

  resources :posts do
    member do
      post :upvote
      post :downvote
    end
    
    collection do
      get :recent
      get :popular
    end
  end
  
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :replies, class_name: "Comment", foreign_key: "parent_id"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments
  
  validates :title, presence: true
  
  def self.author
    author = User.find(self.author_id)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, foreign_key: "author_id"
  has_many :comments
  
  validates :name, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  include PostsHelper
  
  include CommentsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  
  def create
    @reply = Comment.new
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      respond_to do |format|
        format.js
      end
    else
      redirect_to posts_path
    end  
  end
  
  def destroy
    @id = params[:id]
    Comment.find_by(id: @id).destroy
    respond_to do |format|
      format.js
    end
  end
  
  def like
    @comment = Comment.find_by(id: params[:id])
    @comment.likes += 1
    if @comment.save
      respond_to do |format|
        format.js
      end
    else
      redirect_to posts_path
    end
    
  end
  
  def dislike
    @comment = Comment.find_by(id: params[:id])
    @comment.dislikes += 1
    if @comment.save
      respond_to do |format|
        format.js
      end
    else
      redirect_to posts_path
    end
  end
  
  
  private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :parent_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :must_log_in, only: [:new, :create, :edit, :update, :destroy]
 
  
  def index
    @recent = Post.all.order('created_at DESC')
    @popular = Post.all.order('votes DESC' )
    @user = User.new
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def show
    @reply = Comment.new
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.order("created_at DESC")
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.votes = 0
    if @post.save
      redirect_to current_user
    else
      redirect_to posts_path
    end
  end
  
  def edit
    
    @post = Post.find_by(id: params[:id])
    must_be_author(@post)
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    must_be_author(@post)
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    Post.find_by(params[:id]).destroy
    redirect_to posts_path
  end
  
  def upvote    
    @post = Post.find(params[:id])
    @post.votes ||= 0
    @post.votes += 1
    if @post.save
      respond_to do |format|
        format.js 
      end
    end
  end
  
  def downvote
    @post = Post.find(params[:id])
    @post.votes ||= 0
    @post.votes -= 1
    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
    end
  end
  
  def popular
    @popular = Post.all.order('votes DESC')
    respond_to do |format|
      format.js
    end
  end
  
  def recent
    @recent = Post.all.order('created_at DESC')
    respond_to do |format|
      format.js
    end
  end
  
  
  private
  
    def post_params
      params.require(:post).permit(:title, :body)
    end
    
   
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      redirect_to posts_path
    end
  end
  
  def destroy
    log_out
    redirect_to posts_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
      flash[:notice] = "Your sign up was successful!"
    else
      redirect_to posts_path
    end
  end
  
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:notice] = "User was successfully deleted"
    log_out
    redirect_to posts_path
  end
  
  
  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  
  def must_be_user(comment)
    unless comment.user == current_user
      redirect_to posts_path
      flash[:alert] = "You are not authorized for this action"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def must_log_in
    unless logged_in?
      redirect_to posts_path
      flash[:alert] = "You must be logged in to continue"
    end
    
  end
  
  def must_be_author(post)
    unless post.author == current_user
      redirect_to post_path(post)
      flash[:alert] = "You are not authorized for this action"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user=nil
  end
  
  def store_location
    session[:forwarding_url] = request.original_url 
  end
  
  def friendly_redirect(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
<% if @comment.post_id %>
  $('#comments-<%= @comment.post_id %> ')
    .prepend('<div class="level-0"><%= escape_javascript(render partial: "posts/comment", locals: { comment: @comment }) %></div>');
<% end %>

<% if @comment.parent_id %>
  $('#comment-<%= @comment.parent_id %>')
    .append('<%= escape_javascript(render partial: "posts/comment", locals: { comment: @comment }) %>');
  $('#link-<%= @comment.parent_id %>').next().toggle();
<% end %>

$('#link-<%= @comment.id%>').on('click', function(){
    $(this).next().toggle();
});
$('textarea').val('');
$('form').reset();

app/views/comments/destroy.js.erb
$('#comment-<%= @id %>').remove();

app/views/comments/dislike.js.erb
$('#dislikes-<%= @comment.id %>').html('<%= pluralize( @comment.dislikes, "dislike") %>');

app/views/comments/like.js.erb
$('#likes-<%= @comment.id %>').html('<%= pluralize(@comment.likes, "like") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Threadit</title>
  
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,500' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<nav>
  <ul>
    <li><%= link_to "All posts", posts_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Sign out", logout_path, method: :delete %></li>
    <% end %>

  </ul>
</nav>
</header>
  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <div class="content">
    <%= link_to comment.user.name, user_path(comment.user), class: "username" %>
    <span class="small">created <%= time_ago_in_words(comment.created_at)%> ago</span><br>
    
    <% if comment.user == current_user %>
      <span class= "small">
        <%= link_to "Delete comment", comment_path(comment), remote: true, method: :delete %>
      </span>
    <% end %>
    <p> <%= comment.content %> </p>
    
    <%= link_to like_comment_path(comment), remote: true, method: :post do %>
      <i class="material-icons">thumb_up</i>
    <% end %> 
    <span id="likes-<%= comment.id %>" class="small"><%= pluralize(comment.likes, 'like') %></span>
    
    <%= link_to dislike_comment_path(comment), remote: true, method: :post do %>
      <i class="material-icons">thumb_down</i>
    <% end %> 
    <span id="dislikes-<%= comment.id %>" class="small"><%= pluralize(comment.dislikes, 'dislikes') %></span> 
    <% if logged_in? %>
      <span class="reply-link small" id="link-<%= comment.id %>"> | reply</span>
    <% end %>
    <div class="reply-form" >
      <%= form_for @reply, :url => url_for(controller: "comments", action: "create" ), remote: true do |f| %>
        <%= f.text_area :content %><br>
        <%= f.hidden_field :parent_id, value: comment.id %>
        <%= f.submit "POST", class:'btn-2' %>
      <% end %> 
    </div>
  </div>
  
  <% comment.replies.each do |reply|%>
    <%= render partial: 'comment', locals: { comment: reply } %>
  <% end %>
</div>

app/views/posts/_post_form.html.erb
<div class="form-body">
<%= form_for post do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label "text" %><br>
  <%= f.text_area :body %><br>
  <%= f.submit "SUBMIT" %>
        
<% end %>
</div>

app/views/posts/_posts.html.erb
  <div class="post">
    <%= render partial: 'posts/vote', locals:{ post: post } %>
    
    <div class="title">
      <%= link_to post.title, post_path(post), class:"title-link"%> <br>
      <% if post.author %>
        <span class="small">
          created by <%= link_to post.author.name, user_path(post.author) %> 
        <%= time_ago_in_words(post.created_at) %> ago</span><br>
      <% end %>
        <span class="small">
          <%= pluralize(post.comments.count, 'comment') %>
        </span>
    </div>
 
  </div>

app/views/posts/_right_sidebar.html.erb
<% if !logged_in? %>
  <div id="sign">
    <div class="info">
          To post or comment, please <%= link_to "sign in", "#", id: "sign-in-link" %>
          or <%= link_to "sign up", "#", id: "sign-up-link"%>. 
    </div>  
    
      <div class="block" id="up">
        <%= render partial: 'sign_up' %>
      </div>
      <div class="block" id="in">
        <%= render partial: 'sign_in' %>
      </div>
  </div>

<% end %>

app/views/posts/_sign_up.html.erb
<%= form_for @user, :url => url_for(controller: "users", action: "create" ),
    :html => { method: :post } do |f| %>
    
    <%= f.text_field :name, placeholder: "username" %><br>
    <%= f.password_field :password, placeholder: "password" %><br>
    <%= f.password_field :password, placeholder: "confirm password" %><br>
    <%= f.submit "Sign up" %>
<% end %>

app/views/posts/_ugh.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <div class="content">
    <%= link_to comment.user.name, user_path(comment.user) %>
    <span class="small">created <%= time_ago_in_words(comment.created_at)%> ago</span>
    <p> <%= comment.content %> </p>
    <span class="new-reply-link">reply</span>
    
    <div class="reply-form" >
      <%= form_for @reply, :url => url_for(controller: "comments", action: "create" ), remote: true do |f| %>
        <%= f.text_area :content %><br>
        <%= f.hidden_field :parent_id, value: comment.id %>
        <%= f.submit "POST", class:'btn-2' %>
      <% end %> 
    </div>
  </div>
  
  <% comment.replies.each do |reply|%>
    <%= render partial: 'comment', locals: { comment: reply } %>
  <% end %>
</div>

app/views/posts/downvote.js.erb
$("#vote-<%= @post.id%>").html("<%= @post.votes %>");

app/views/posts/edit.html.erb
<div class="left">
</div>

<div class="center">
  <div class="form">
    <div class="form-title">
      Edit post
    </div>
    <%= render partial: 'post_form', locals: { post: @post } %>
</div>
</div>

app/views/posts/index.html.erb
<div class="index">
  <div class="show">
      <div class="right">
        <%= render partial: 'right_sidebar' %>
     </div>
      <div class="tabs">
        <div class="btn">
          <%= button_to "CREATE NEW POST", new_post_path, method: :get  %>
        </div>
        <div class="tab" id="popular">
         <%= link_to "POPULAR", popular_posts_path, remote: true, id: "popular-link" %>
        </div>
        <div class="tab active" id="recent">
         <%= link_to "RECENT", recent_posts_path, remote: true, id:"recent-link" %>
        </div>
      </div>
      
      <div class="posts" id="posts">
        <%= render partial: 'posts', collection: @recent, as: :post %>
      </div>
    
    
  </div>
</div>

app/views/posts/new.html.erb
<div class="left">
</div>

<div class="center">
  <div class="form">
    <div class="form-title">
      Create a new post
    </div>
    <%= render partial: 'post_form', locals: { post: @post } %>
</div>
</div>

app/views/posts/popular.js.erb
$('#posts')
  .html("<%= escape_javascript(render(partial: 'posts', collection: @popular, as: :post)) %>")

app/views/posts/recent.js.erb
$('#posts')
  .html("<%= escape_javascript(render(partial: 'posts', collection: @recent, as: :post)) %>")

app/views/posts/show.html.erb
<div class="top">
  
 

  <div class="show">
     <%= render partial: 'vote', locals: { post: @post } %>
    <h3><%= @post.title %></h3> <br>
    <% if @post.author %>
      <span class="small">  
        created by <%= link_to @post.author.name, user_path(@post.author) %> 
        <%= time_ago_in_words(@post.created_at) %> ago 
      </span><br>
    <% end %> 
    
    <% if @post.author == current_user %>
      <span class="small">
        <%= link_to "Edit post", edit_post_path(@post) %> | 
        <%= link_to "Delete post", post_path(@post), method: :delete %>
      </span>
    <% end %>
    <p><%= @post.body %></p>
  </div>
  
  
</div>
        
      
  
  
</div>

<div class="bottom">
  
        <div class="comment-container">
         
            <h3>All comments</h3>
     
          <% if logged_in? %>
          <div class="new-comment">
            <%= form_for @comment, :url => url_for(controller: "comments", action: "create" ), remote: true do |f| %>
              <%= f.text_area :content %><br>
              <%= f.hidden_field :post_id, value: @post.id %>
              <%= f.submit "POST", class:'btn-2' %>
            <% end %>          
          </div>
          <% else %>
            <em>You must be logged in to comment.</em>
          <% end %>
          <div id="comments-<%= @post.id %>">
            <% if !@comments.nil? %>
              <% @comments.each do |comment|%>
                <div class="level-0">
                  <%= render partial: "comment", locals: { comment: comment } %>
               </div>
              
              <% end %>
            
            <% end %>
          </div>
         
        </div>
      
 </div>

app/views/posts/upvote.js.erb
$("#vote-<%= @post.id%>").html("<%= @post.votes %>");

app/views/users/show.html.erb
<div class="top">
  <div class="show">
    <h1><%= @user.name %></h1>
    <span class="small">member for <%= time_ago_in_words(@user.created_at) %></span><br>
    <% if @user == current_user %>
      <span class="small">
        <%= link_to "Delete account", user_path(@user), method: :delete %>
      </span>
    <% end %>
  </div>
</div>

<div class="bottom">
  
  <div class="show">
    <h2><%= @user.name %>'s posts </h2>
      <div class="posts" id="posts">
        <%= render partial: 'posts/posts', collection: @posts, as: :post %>
      </div>
  </div>
</div>